---
- name: Install go-specific apt packages
  sudo: true
  apt: name={{ item }} state=latest
  with_items:
    - vim-syntax-go
    - vim-gocomplete
- name: Download Golang binary distribution
  get_url:
      url=https://storage.googleapis.com/golang/{{ go_archive_file }}
      dest={{ document_root }}/{{ go_archive_file }}
- name: Create ~/opt folder
  file:
      path=/home/vagrant/opt
      state=directory
- name: Unpack the Go binary distribution
  unarchive:
      copy=no
      src={{ document_root }}/{{ go_archive_file }}
      dest=/home/vagrant/opt
      creates=/home/vagrant/opt/go
- name: Add go path settings in .bashrc_mods
  lineinfile: dest=/home/vagrant/.bashrc_mods line="{{ item }}" insertafter=EOF
  with_items:
    - 'export GOROOT=~/opt/go'
    - 'export GOPATH=~/code/go'
    - 'export PATH=~/opt/go/bin:$PATH'
- name: Create go code folder
  file:
    dest=/home/vagrant/code/go/src/github.com/{{ github_user }}
    state=directory
    recurse=yes
    owner=vagrant
    group=vagrant
