---
- hosts: all
  sudo: true
  vars:
      document_root: /vagrant
  pre_tasks:
      - name: Update apt cache and upgrade
        apt: update_cache=yes cache_valid_time=3600 upgrade=yes
      - name: Install stuff from Aptitude
        apt: name={{ item }} state=installed
        with_items:
          - git
          - tig
          - vim
  roles:
      - golang
      - samuelsenv
