---
- name: Check out the user's run configuration files repo from github
  git:
    repo=https://github.com/{{ github_user }}/{{ dotfiles_reponame }}.git
    dest=/home/vagrant/{{ dotfiles_reponame }}
    update=yes
- name: Symlink config files in rc folder
  file: src=/home/vagrant/{{ dotfiles_reponame }}/{{ item }} dest=/home/vagrant/{{ item }} state=link
  with_items:
    - .bashrc_mods
    - .bash_aliases
    - .tmux.conf
    - .vimrc
    - .vim
- name: Create empty .bash_aliases_local file
  shell:
      echo '# Add local aliases here' > /home/vagrant/.bash_aliases_local
      creates=/home/vagrant/.bash_aliases_local
- name: Include .bashrc_mods in .bashrc
  lineinfile:
      "dest=/home/vagrant/.bashrc line='. ~/.bashrc_mods # Include local mods' insertafter=EOF"
