---
- name: Install apt packages for YouCompleteMe vim completion engine
  sudo: yes
  apt:
    name={{ item }} state=latest
  with_items:
    - build-essential
    - cmake
    - python-dev
- name: Check out YouCompleteMe
  git:
    repo=https://github.com/Valloric/YouCompleteMe.git
    dest=/home/vagrant/src/YouCompleteMe
- name: Symlink YouCompleteMe to ~/vim/bundle
  file:
    src=/home/vagrant/src/YouCompleteMe
    dest=/home/vagrant/.vim/bundle/YouCompleteMe
    state=link
- name: Compile YouCompleteMe binaries
  command: ./install.sh --clang-completer
    chdir=/home/vagrant/src/YouCompleteMe
    creates=/home/vagrant/src/YouCompleteMe/python/ycm/youcompleteme.pyc

